account/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
import account.views
from account import views

app_name = 'account'

urlpatterns = [

    path('loginn', views.loginPage, name='login'),
    path('registrati', views.paginaRegistrazione, name='registrati'),
    path('logout/', views.logoutUser, name="logout"),
    ]

ecommerce1/urls.py
from django.contrib import admin
from django.contrib.auth.decorators import login_required
from django.contrib.staticfiles.storage import staticfiles_storage
from django.urls import path, include

from django.conf.urls.static import static
from django.conf import settings
from django.views.generic import RedirectView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('store.urls')),
    path('account/', include('account.urls', namespace='account')),
    path(
        "favicon.ico",
        RedirectView.as_view(url=staticfiles_storage.url("favicon.ico")),
    ),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

store/urls.py
from django.contrib.auth.decorators import login_required
from django.urls import path, re_path
from . import views

urlpatterns = [
    path('', views.store, name="store"),
    path('carrello/', views.carrello, name="carrello"),
    path('checkout/', views.checkout, name="checkout"),
    path('update_item/', views.updateItem, name="update_item"),
    path('process_order/', views.processOrder, name="process_order"),
    path('<int:id>/', views.product_detail, name='product_detail'),
    path('cerca/', views.cerca, name='cerca'),
    path('profile', views.MyorderConf, name='profile'),
    re_path(r'^password/$', views.PasswordChangeView, name='modica-password'),
    path('Myorder/', views.MyorderConf, name='Myorder'),
    path('add-item', views.ItemAdd.as_view(), name='item-add'),
    path('order-conf', views.orderConf, name='order-conf'),
    path('order-conf-ajax', views.orderConfajax, name='order-conf-ajax'),
]

store/models.py
from django.db import models
from django.contrib.auth.models import User
from store.models import *


class Prodotto(models.Model):
    name = models.CharField(max_length=200)
    price = models.DecimalField(max_digits=7, decimal_places=2)
    digital = models.BooleanField(default=False, null=True, blank=False)
    image = models.ImageField(null=True, blank=True)
    description = models.TextField(blank=True)

    def __str__(self):
        return self.name

    @property
    def imageURL(self):
        try:
            url = self.image.url
            return url
        except:
            url = 'static/immagini/no_image.png'
        return url


class Item(models.Model):
    prodotto = models.ForeignKey(Prodotto, on_delete=models.SET_NULL, null=True)
    quantita = models.IntegerField(default=0, null=True, blank=True)
    date_added = models.DateTimeField(auto_now_add=True)

    def get_name(self):
        return self.prodotto.name

    @property
    def get_total(self):
        total = self.prodotto.price * self.quantita
        return total


class Order(models.Model):
    # facciamo la relazione tra il cliente e l'ordine, se l'utente è eliminato non viene eliminato l'ordine
    user = models.ForeignKey(User, on_delete=models.CASCADE, null=True, blank=True)  # un solo profilo per cliente
    data_ordine = models.DateTimeField(auto_now_add=True)
    complete = models.BooleanField(default=False)
    transaction_id = models.CharField(max_length=100, null=True)
    items = models.ManyToManyField(Item, blank=True)

    def __str__(self):
        return str(self.id)

    @property
    def shipping(self):
        shipping = False
        orderitems = self.orderitem_set.all()
        for i in orderitems:
            if i.prodotto.digital == False:
                shipping = True
        return shipping

    def get_total(self):
        total = 0
        for order_item in self.items.all():
            total += order_item.get_final_price()
        return total

    @property
    def get_cart_total(self):
        orderitems = self.orderitem_set.all()
        total = sum([item.get_total for item in orderitems])
        return total

    @property
    def get_cart_items(self):
        orderitems = self.orderitem_set.all()
        total = sum([item.quantita for item in orderitems])
        return total

    def getitems(self):
        total = "  "
        for order_item in self.orderitem_set.all():
            total += (order_item.get_name() + " pezzi: " + str(order_item.quantita)) + ", "
        return total


class OrderItem(models.Model):
    prodotto = models.ForeignKey(Prodotto, on_delete=models.SET_NULL, null=True)
    order = models.ForeignKey(Order, on_delete=models.SET_NULL, null=True)  # un solo ordine può avere tanti item
    quantita = models.IntegerField(default=0, null=True, blank=True)
    date_added = models.DateTimeField(auto_now_add=True)

    @property
    def get_total(self):
        total = self.prodotto.price * self.quantita
        return total

    def get_name(self):
        return self.prodotto.name

    def get_qta(self):
        return self.quantita


class ShippingAddress(models.Model):
    # ci metto il cliente così se un ordine dovesse venir cancellato, mi resta cmq salvato l'indirizzo di spedizione del cliente
    user = models.ForeignKey(User, on_delete=models.SET_NULL, null=True, blank=True)
    order = models.ForeignKey(Order, on_delete=models.SET_NULL, null=True)

    indirizzo = models.CharField(max_length=200, null=True)
    citta = models.CharField(max_length=200, null=True)
    provincia = models.CharField(max_length=200, null=True)
    cap = models.IntegerField(null=True)
    date_added = models.DateTimeField(auto_now_add=True)


def __str__(self):
    return self.id


class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE, related_name='profile')

    def __str__(self):
        return self.user.first_name

store/views.py
import datetime
import json

from django.contrib import messages
from django.contrib.auth import update_session_auth_hash
from django.contrib.auth.decorators import login_required
from django.contrib.auth.forms import PasswordChangeForm
from django.http import JsonResponse
from django.shortcuts import render, get_object_or_404, redirect
from django.urls import reverse_lazy
from django.views.generic import CreateView

from account.forms import ItemCrispyForm
from .models import *
from .utils import cartData, ordineGuest


def store(request):
    data = cartData(request)
    cartItems = data['cartItems']

    prodotto = Prodotto.objects.all

    context = {'prodotto': prodotto, 'cartItems': cartItems}
    return render(request, 'store/store.html', context)


def carrello(request):
    data = cartData(request)
    cartItems = data['cartItems']
    order = data['order']
    items = data['items']

    context = {'items': items, 'order': order, 'cartItems': cartItems}

    return render(request, 'store/carrello.html', context)


def checkout(request):
    data = cartData(request)

    cartItems = data['cartItems']
    order = data['order']
    items = data['items']

    context = {'items': items, 'order': order, 'cartItems': cartItems}
    return render(request, 'store/checkout.html', context)


def updateItem(request):
    data = json.loads(request.body)
    prodottoId = data['prodottoId']
    action = data['action']
    print('Action:', action)
    print('Product:', prodottoId)

    user = request.user
    prodotto = Prodotto.objects.get(id=prodottoId)
    order, created = Order.objects.get_or_create(user=user, complete=False)

    orderItem, created = OrderItem.objects.get_or_create(order=order, prodotto=prodotto)

    if action == 'add':
        orderItem.quantita = (orderItem.quantita + 1)
    elif action == 'remove':
        orderItem.quantita = (orderItem.quantita - 1)

    orderItem.save()

    if orderItem.quantita <= 0:
        orderItem.delete()

    return JsonResponse('Item was added', safe=False)


def processOrder(request):
    transaction_id = datetime.datetime.now().timestamp()
    data = json.loads(request.body)

    if request.user.is_authenticated:
        user = request.user
        order, created = Order.objects.get_or_create(user=user, complete=False)

        if order.shipping == True:
            ShippingAddress.objects.create(
                user=user,
                order=order,
                indirizzo=data['shipping']['indirizzo'],
                citta=data['shipping']['citta'],
                provincia=data['shipping']['provincia'],
                cap=data['shipping']['cap'],

            )

    else:
        user, order = ordineGuest(request, data)

    total = float(data['form']['total'])
    order.transaction_id = transaction_id

    # serve per evitare che un utente riesca a comprare il prodotto pagandolo alla cifra che vuole, andiamo a controllare se il totale che viene pagato
    # è uguale al totale del carrello e solo in tal caso l'ordine sarà poi processato

    if total == order.get_cart_total:
        order.complete = True
    order.save()

    if order.shipping == True:
        ShippingAddress.objects.create(
            user=user,
            order=order,
            indirizzo=data['shipping']['indirizzo'],
            citta=data['shipping']['citta'],
            provincia=data['shipping']['provincia'],
            cap=data['shipping']['cap'],
        )

    return JsonResponse('pagamento completo', safe=False)


def product_detail(request, id):
    prodotto = get_object_or_404(Prodotto,
                                 id=id,
                                 )

    return render(request,
                  'store/detail.html',
                  {'prodotto': prodotto
                   })


def cerca(request, ):
    """
    Barra di ricerca
    :return: ritorna la pagina che mostra i risultati della ricerca
    """
    if "q" in request.GET:

        querystring = request.GET.get("q")
        # print(querystring)
        if len(querystring) == 0:
            return redirect("/cerca/")
        prodotti = Prodotto.objects.filter(name__icontains=querystring)
        print(prodotti)
        context = {"prodotti": prodotti}
        return render(request, 'store/cerca.html', context)
    else:
        return render(request, 'store/cerca.html')


@login_required(login_url='/login')
def ProfileView(request):
    form = []
    user = request.user.id
    context1 = {"profile": Profile.objects.get(user=request.user)}
    return render(request, 'store/profile.html', context1)


class PasswordChange(object):
    pass


@login_required(login_url='/login')
def PasswordChangeView(request):
    if request.method == 'POST':
        form = PasswordChangeForm(request.user, request.POST)
        if form.is_valid():
            user = form.save()
            update_session_auth_hash(request, user)  # Important!
            messages.success(request, 'Password modificata con Successo!')
            return render(request, 'store/store.html')
        else:
            messages.error(request, 'Correggi gli errori e riprova.')
    else:
        form = PasswordChangeForm(request.user)
    return render(request, 'store/password_change.html', {
        'form': form
    })


def orderConfajax(request):
    # product = Product.objects.get(id=id)
    # print(request.POST.get('username'))
    data = {'is_taken': False}
    if request.method == 'POST' and request.user.is_authenticated:
        tt = Order.objects.get(id=request.POST.get('username'))
        tt.complete = True
        tt.save()

        data = {'is_taken': True}

        return JsonResponse(data)
    return JsonResponse(data)


@login_required(login_url='/login')
def orderConf(request):
    now = datetime.datetime.now()
    start_date = now.strftime("%m")
    start_date = str(int(start_date) - 1)

    print(start_date, "startdate")
    items = {}
    for x in Order.objects.filter(data_ordine__month=start_date):
        items[int(x.data_ordine.strftime("%d"))] = 0

    for x in Order.objects.filter(data_ordine__month=start_date):
        items[int(x.data_ordine.strftime("%d"))] = x.items.count() + items[int(x.data_ordine.strftime("%d"))]

    list = [(k, v) for k, v in items.items()]
    print(items)

    norder = Order.objects.filter(complete=True)

    norder2 = Order.objects.filter(complete=False)

    context = {'items': list, 'norder': norder, 'norder2': norder2}
    return render(request, 'store/totordini.html', context)


@login_required(login_url='/login')
def MyorderConf(request):
    norder = Order.objects.filter(user=request.user)
    print(norder)
    context = {'norder': norder}
    return render(request, 'store/profile.html', context)



class ItemAdd(CreateView):
    model = Prodotto
    template_name = 'store/add-item.html'
    form_class = ItemCrispyForm

    success_url = reverse_lazy('store')

store/templates/store/add-item.html
{% extends 'store/main.html' %}#
{% load static %}
{% include crispy_tags %}

{% load crispy_forms_tags %}

{% block title %}Aggiungi un nuovo prodotto{% endblock %}



{% block content %}

    <div class="container">
        <div class="thead-dark">
            <h1>Aggiungi un nuovo Prodotto</h1>
            {% crispy form %}

        </div>

    </div>
{% endblock %}

store/templates/store/carrello.html
{% extends 'store/main.html' %}
{% load static %}
{% block content %}

    <div class="row">
        <div class="col-lg-12">
            <div class="box-element">

                <div class="form-inline my-2 my-lg-0">
            <span class="user">
                <div align="Right">
                    {% if request.user.is_authenticated %}
                        <a href="{% url 'store' %}" class="btn btn-success">Continua lo Shopping</a>
                    {% else %}
                        <a href="{% url 'store' %}" class="btn btn-success">Continua lo Shopping</a>
                        <a href="{% url 'account:login' %}" class="btn btn-success">Effettua il Login prima di continuare</a>
                    {% endif %}
                </div>
            </span>
                    <br>
                    <br>

                    <table class="table">
                        <tr>
                            <th><h5>Prodotto: <strong>{{ order.get_cart_items }}</strong></h5></th>
                            <th><h5>Totale: <strong>{{ order.get_cart_total|floatformat:2 }}€</strong></h5></th>
                            <th>
                                <a style="float:right; margin:5px" class="btn btn-success" href="{% url 'checkout' %}">Acquista
                                    ora</a>
                            </th>


                        </tr>
                    </table>
                </div>

                <br>

                <div class="box-element">
                    <div class="cart-row">
                        <div style="flex:2"></div>
                        <div style="flex:2"><strong>Prodotto</strong></div>
                        <div style="flex:1"><strong>Prezzo</strong></div>
                        <div style="flex:1"><strong>Quantità</strong></div>
                        <div style="flex:1"><strong>Totale</strong></div>
                    </div>

                    {% for items in items %}
                        <div class="cart-row">
                            <div style="flex:2"><img class="row-image" src="{{ items.prodotto.imageURL }}"></div>
                            <div style="flex:2">{{ items.prodotto.name }} </div>
                            <div style="flex:1">{{ items.prodotto.price|floatformat:2 }}€</div>
                            <div style="flex:1">
                                <p class="quantity">{{ items.quantita }}</p>
                                <div class="quantity">
                                    <img data-prodotto="{{ items.prodotto.id }}" data-action="add"
                                         class="chg-quantity update-cart" src="{% static  'immagini/freccia-su.png' %}">

                                    <img data-prodotto="{{ items.prodotto.id }}" data-action="remove"
                                         class="chg-quantity update-cart"
                                         src="{% static  'immagini/freccia-giu.png' %}">
                                </div>
                            </div>
                            <div style="flex:1"><p>{{ items.get_total }}€</p></div>
                        </div>
                    {% endfor %}
                </div>
            </div>
        </div>
{% endblock content %}

store/templates/store/checkout.html
{% extends 'store/main.html' %}
{% load static %}
{% block content %}
    <div class="row">
        <div class="col-lg-6">
            <div class="box-element" id="form-wrapper">
                <form id="form">
                    {% csrf_token %}
                    <div id="user-info">
                        <div class="form-field">
                            <input required class="form-control" type="text" name="name" placeholder="Nome..">
                        </div>
                        <div class="form-field">
                            <input required class="form-control" type="email" name="email" placeholder="Email..">
                        </div>
                    </div>

                    <div id="shipping-info">
                        <hr>
                        <p>Indirizzo di Spedizione:</p>
                        <hr>
                        <div class="form-field">
                            <input required class="form-control" type="text" name="indirizzo" placeholder="Indirizzo..">
                        </div>
                        <div class="form-field">
                            <input required class="form-control" type="text" name="citta" placeholder="Città..">
                        </div>
                        <div class="form-field">
                            <input required class="form-control" type="text" name="provincia" placeholder="Provincia..">
                        </div>
                        <div class="form-field">
                            <input required class="form-control" type="number" name="cap"
                                   placeholder="Cap..   (solo numeri)">
                        </div>
                    </div>

                    <hr>
                    <input id="form-button" class="btn btn-success btn-block" type="submit" value="Continua">
                </form>
            </div>

            <br>
            <div class="box-element hidden" id="payment-info">
                <small>Paypal</small>
                <div id="paypal-button-container"></div>
                <!--button id="make-paymentpaypal">Paga con Paypal</button> -->
            </div>

        </div>

        <div class="col-lg-6">
            <div class="box-element"> <span class="user">
                <div align="Right">
                    {% if request.user.is_authenticated %}
                        <a class="btn btn-outline-dark" href="{% url 'carrello' %}">&#x2190; Torna al Carrello</a>
                    {% else %}
                        <a class="btn btn-outline-dark" href="{% url 'carrello' %}">&#x2190; Torna al Carrello</a>
                        <a href="{% url 'account:login' %}" class="btn btn-outline-dark">Effettua il Login</a>
                    {% endif %}
                </div>
            </span>
                <hr>
                <h3>Riepilogo dell'Ordine</h3>
                <hr>
                {% for items in items %}
                    <div class="cart-row">
                        <div style="flex:2"><img class="row-image" src="{{ items.prodotto.imageURL }}"></div>
                        <div style="flex:2"><p>{{ items.prodotto.name }}</p></div>
                        <div style="flex:1"><p>€ {{ items.prodotto.price }}</p></div>
                        <div style="flex:1"><p>{{ items.quantita }}</p></div>
                    </div>
                {% endfor %}
                <h5>Prodotti: {{ order.get_cart_items }}</h5>
                <h5>Totale: € {{ order.get_cart_total|floatformat:2 }}</h5>
            </div>
        </div>
    </div>

    <script src="https://www.paypal.com/sdk/js?client-id=ASiRXQeFdGrg29dOAeExsIKxZ5hsncvEtXRYeVMWH-M-YJlP1PNlN-6DDL6q2vGSHDp0ceTMc61V5j25&currency=EUR&disable-funding=mybank,sofort"></script>

    <script>
        var total = '{{ order.get_cart_total }}'
        paypal.Buttons({

            style: {
                color: 'blue',
                shape: 'pill',
                label: 'pay',

            },

            // Set up the transaction
            createOrder: function (data, actions) {
                return actions.order.create({
                    purchase_units: [{
                        amount: {
                            value: parseFloat(total).toFixed(2)
                        }
                    }]
                });
            },

            // Finalize the transaction
            onApprove: function (data, actions) {
                return actions.order.capture().then(function (details) {
                    submitFormData()
                });
            }


        }).render('#paypal-button-container');
    </script>
    <script type="text/javascript">
        var shipping = '{{ order.shipping }}'
        var total = '{{ order.get_cart_total }}'

        if (shipping == 'False') {
            document.getElementById('shipping-info').innerHTML = ''
        }

        //se l'utente non è un anon user ovvero loggato allora nascondo le info utente (nome, email)
        if (user != 'AnonymousUser') {
            document.getElementById('user-info').innerHTML = ''
        }

        if (shipping == 'False' && user != 'AnonymousUser') {
            //nascondo il form perchè l'utente è loggato e la shipping non serve (prodotto digitale) nascondo tutto.
            document.getElementById('form-wrapper').classList.add("hidden");
            //mostro il pagamento se l'utente è loggato e compra un prodotto digitale
            document.getElementById('payment-info').classList.remove("hidden")
        }

        var form = document.getElementById('form')
        csrftoken = form.getElementsByTagName("input")[0].value
        console.log('Newtoken: ', form.getElementsByTagName("input")[0].value)
        form.addEventListener('submit', function (e) {
            e.preventDefault()
            console.log('form inviato...')
            document.getElementById('form-button').classList.add('hidden')
            document.getElementById('payment-info').classList.remove('hidden')
        })

        /* document.getElementById('make-paymentpaypal').addEventListener('click', function (e){
             submitFormData()
         }) **/

        function submitFormData() {
            console.log('pagamaneto clicckato')

            var userFormData = {
                'name': null,
                'email': null,
                'total': total,
            }

            var shippingInfo = {
                'indirizzo': null,
                'provincia': null,
                'citta': null,
                'cap': null,

            }

            if (shipping !== 'False') {
                shippingInfo.indirizzo = form.indirizzo.value
                shippingInfo.provincia = form.provincia.value
                shippingInfo.citta = form.citta.value
                shippingInfo.cap = form.cap.value

            }

            if (user == 'AnonymousUser') {
                userFormData.name = form.name.value
                userFormData.email = form.email.value
            }

            console.log('info spedizione:', shippingInfo)
            console.log('info utente:', userFormData)

            var url = "/process_order/"
            fetch(url, {
                method: 'POST',
                headers: {
                    'Content-Type': 'application/json',
                    'X-CSRFToken': csrftoken,
                },
                body: JSON.stringify({'form': userFormData, 'shipping': shippingInfo})

            })
                .then((response) => response.json())
                .then((data) => {
                    console.log('successo:', data);
                    alert('Transazione andata a buon fine');

                    cart = {}
                    document.cookie = 'carrello=' + JSON.stringify(cart) + ";domain=;path=/"
                    window.location.href = "{% url 'store' %}"
                })
        }
    </script>

{% endblock content %}

store/templates/store/detail.html
{% extends "store/main.html" %}
{% load static %}

{% block title %}
    {{ prodotto.name }}
{% endblock %}
<link rel="icon" href=type="image/icon>


{% block content %}
    <div class="product-detail">
        <img src="
                {% if prodotto.imageURL %}{{ prodotto.imageURL }}{% else %}{% static 'immagini/no_image.png' %}{% endif %}">

        <h1>{{ prodotto.name }}</h1>
        <h2>

        </h2>
        <button data-prodotto="{{ prodotto.id }}" data-action="add"
                class="btn btn-outline-secondary add-btn update-cart">Add to Cart
        </button>
        <p class="price">€{{ prodotto.price }}

            {{ prodotto.description|linebreaks }}
    </div>
{% endblock %}

store/templates/store/main.html
<!DOCTYPE html>
{% load static %}
<html>
<meta charset="utf-8"/>
<title>{% block title %}Tiri Vispi Weasley{% endblock %}</title>
<link rel="icon" href="{% static 'favicon.ico' %}" type="image/icon type">
<link href="{% static 'css/main.css' %}" rel="stylesheet">


<meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, minimum-scale=1"/>

<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css"
      integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">

<link rel="stylesheet" type="text/css" href="{% static 'css/main.css' %}">

<script type="text/javascript">
    var user = '{{request.user}}'

    function getToken(name) {
        var cookieValue = null;
        if (document.cookie && document.cookie !== '') {
            var cookies = document.cookie.split(';');
            for (var i = 0; i < cookies.length; i++) {
                var cookie = cookies[i].trim();
                // Does this cookie string begin with the name we want?
                if (cookie.substring(0, name.length + 1) === (name + '=')) {
                    cookieValue = decodeURIComponent(cookie.substring(name.length + 1));
                    break;
                }
            }
        }
        return cookieValue;
    }

    var csrftoken = getToken('csrftoken')

    function getCookie(name) {
        var cookieArr = document.cookie.split(";");
        for (var i = 0; i < cookieArr.length; i++) {
            var cookiePair = cookieArr[i].split("=");

            if (name == cookiePair[0].trim()) {
                // Decode the cookie value and return
                return decodeURIComponent(cookiePair[1]);
            }
        }
        return null;
    }

    var cart = JSON.parse(getCookie('carrello'))

    if (cart == undefined) {
        cart = {}
        console.log('carrello creato!', cart)
        document.cookie = 'carrello=' + JSON.stringify(cart) + ";domain=;path=/"
    }
    console.log('Carrello:', cart)
</script>

</head>
<body>

<div id="progressbar"></div>
<div id="scrollPath"></div>
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
    <a class="navbar-brand" href="{% url 'store' %}" style="width: 35%"> <img src="{% static 'immagini/Titolo.png' %}"
                                                                              width="55%"> </a>
    <form class="form-inline my-2 my-lg-0" action="{% url 'cerca' %}">
        <input name="q" class="inputCerca form-control mr-sm-2" type="search" placeholder="cerca" aria-label="Search">
        <button class="btn btn-outline-info my-2 my-sm-0" type="submit">Cerca</button>
    </form>

    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent"
            aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav mr-auto">
            <li class="nav-item active">
                <a class="nav-link" href="{% url 'store' %}"><span class="sr-only">(current)</span></a>
            </li>
        </ul>
    </div>

    <div class="form-inline btn-group dropdown y-2 my-lg-0">
                <span class="user">
                    <div align="Right">
                        {% if request.user.is_authenticated %}
                            {% if request.user.is_superuser %}
                                <div class="dropdown-menu" aria-labelledby="dropdownMenuButton" align="right">
                                <a class="dropdown-item" href="{% url 'item-add' %}">Add product</a>
                                <a class="dropdown-item" href="/admin" id="id_btn_home"><b>Pannello di Admin</b></a>
                                <a class="dropdown-item" href="{% url 'order-conf' %}">controlla ordini</a>
                                <a class="dropdown-item" href="{% url 'Myorder' %}">I miei Ordini</a>
                                <a class="dropdown-item" href="{% url 'account:logout' %}">Logout</a>
                                </div>

                            {% endif %}
                            <button class="btn btn-secondary dropdown-toggle" type="button" id="dropdownMenuButton"
                                    data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                    {{ request.user }}
                                </button>
                            <div class="dropdown-menu" aria-labelledby="dropdownMenuButton" align="right">
                                <a class="dropdown-item" href="{% url 'Myorder' %}">I miei Ordini</a>
                                <a class="dropdown-item" href="{% url 'account:logout' %}">Logout</a>
                              </div>
                        {% else %}
                            <a href="{% url 'account:login' %}" class="btn btn-success">Login</a>
                        {% endif %}
                    </div>
                </span>
        <a href="{% url 'carrello' %}">
            <img id="cart-icon" src="{% static 'immagini/carrello.png' %}">
        </a>
        <p id="cart-total">{{ cartItems }}</p>
    </div>

</nav>

<div class="container">
    <br>
    {% block content %}


    {% endblock content %}
</div>

<script src="https://code.jquery.com/jquery-3.1.1.min.js">

    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js"
            integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo"
            crossorigin="anonymous"></script>

<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js"
        integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6"
        crossorigin="anonymous"></script>

<script type="text/javascript" src="{% static 'js/cart.js' %}"></script>
<script type="text/javascript">
    let progress = document.getElementById('progressbar');
    let totalHeight = document.body.scrollHeight - window.innerHeight;
    window.onscroll = function () {
        let progressHeight = (window.pageYOffset / totalHeight) * 110;
        progress.style.height = progressHeight + "%";
    }

</script>

</body>
</html>